-- SKLADAPLAN — Optimization / atomic application
-- Run after SUPABASE_P0.sql (or after the current base migration).
-- No business data is deleted.

begin;

create table if not exists public.warehouse_optimizations (
  id bigint generated by default as identity primary key,
  status text not null default 'applied',
  warehouse text,
  source_zones jsonb not null default '[]'::jsonb,
  target_zone text,
  capacity integer not null default 40,
  planned_move_count integer not null default 0,
  planned_box_count integer not null default 0,
  applied_move_count integer not null default 0,
  applied_box_count integer not null default 0,
  freed_pallet_count integer not null default 0,
  operator text,
  created_at timestamptz not null default now(),
  applied_at timestamptz
);

create table if not exists public.warehouse_optimization_moves (
  id bigint generated by default as identity primary key,
  optimization_id bigint not null references public.warehouse_optimizations(id) on delete cascade,
  source_warehouse text,
  source_zone text,
  source_pallet text,
  target_warehouse text,
  target_zone text,
  target_pallet text,
  article text,
  box_count integer not null default 0,
  box_ids jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.warehouse_optimizations enable row level security;
alter table public.warehouse_optimization_moves enable row level security;

drop policy if exists warehouse_optimizations_select_authenticated on public.warehouse_optimizations;
create policy warehouse_optimizations_select_authenticated
  on public.warehouse_optimizations for select to authenticated using (true);

drop policy if exists warehouse_optimization_moves_select_authenticated on public.warehouse_optimization_moves;
create policy warehouse_optimization_moves_select_authenticated
  on public.warehouse_optimization_moves for select to authenticated using (true);

drop policy if exists warehouse_optimizations_insert_admin on public.warehouse_optimizations;
create policy warehouse_optimizations_insert_admin
  on public.warehouse_optimizations for insert to authenticated
  with check (public.skladaplan_is_admin());

drop policy if exists warehouse_optimization_moves_insert_admin on public.warehouse_optimization_moves;
create policy warehouse_optimization_moves_insert_admin
  on public.warehouse_optimization_moves for insert to authenticated
  with check (public.skladaplan_is_admin());

-- The browser never updates boxes directly for an optimization.
-- The whole plan is validated and applied in one PostgreSQL transaction.
drop function if exists public.sp_apply_warehouse_optimization(jsonb,integer,text,text,jsonb);
create or replace function public.sp_apply_warehouse_optimization(
  p_plan jsonb,
  p_capacity integer,
  p_operator text,
  p_target_zone text,
  p_source_zones jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_operator text := coalesce(auth.jwt()->>'email', nullif(trim(p_operator),''));
  v_capacity integer := coalesce(p_capacity,40);
  v_opt_id bigint;
  v_move jsonb;
  v_box_ids bigint[];
  v_box_id bigint;
  v_count integer;
  v_actual integer;
  v_source_warehouse text;
  v_source_zone text;
  v_source_pallet text;
  v_target_warehouse text;
  v_target_zone text;
  v_target_pallet text;
  v_article text;
  v_target_warehouse_id bigint;
  v_target_location_id bigint;
  v_target_pallet_id bigint;
  v_target_count integer;
  v_target_article text;
  v_source_distinct_count integer;
  v_freed_pallet_count integer := 0;
  v_applied_box_count integer := 0;
  v_applied_move_count integer := 0;
  v_existing_source_count integer;
  v_moved_from_source integer;
  v_source_after integer;
  v_barcode text;
  v_reason text := 'optimization';
begin
  if not public.skladaplan_is_admin() then
    raise exception 'FORBIDDEN: admin role required';
  end if;

  if jsonb_typeof(p_plan) <> 'array' or jsonb_array_length(p_plan) = 0 then
    raise exception 'EMPTY_OPTIMIZATION_PLAN';
  end if;

  if v_capacity < 1 or v_capacity > 1000 then
    raise exception 'INVALID_PALLET_CAPACITY: %', v_capacity;
  end if;

  if nullif(trim(p_target_zone),'') is null then
    raise exception 'TARGET_ZONE_REQUIRED';
  end if;

  create temporary table if not exists tmp_skladaplan_opt_boxes (
    box_id bigint primary key
  ) on commit drop;
  truncate tmp_skladaplan_opt_boxes;

  create temporary table if not exists tmp_skladaplan_opt_targets (
    pallet_id bigint primary key,
    warehouse_id bigint,
    location_id bigint,
    pallet_number text,
    current_count integer not null,
    target_article text
  ) on commit drop;
  truncate tmp_skladaplan_opt_targets;

  -- Resolve the target warehouse from the plan. All moves must use one warehouse.
  select distinct nullif(trim(x->>'target_warehouse'),'')
    into v_target_warehouse
  from jsonb_array_elements(p_plan) x
  where nullif(trim(x->>'target_warehouse'),'') is not null;

  if v_target_warehouse is null then
    raise exception 'TARGET_WAREHOUSE_REQUIRED';
  end if;

  if exists (
    select 1
    from (
      select distinct nullif(trim(x->>'target_warehouse'),'') as warehouse
      from jsonb_array_elements(p_plan) x
    ) q
    where q.warehouse is distinct from v_target_warehouse
  ) then
    raise exception 'MULTIPLE_TARGET_WAREHOUSES_NOT_ALLOWED';
  end if;

  select id into v_target_warehouse_id
  from public.warehouses
  where name = v_target_warehouse
  limit 1;
  if v_target_warehouse_id is null then
    raise exception 'WAREHOUSE_NOT_FOUND: %', v_target_warehouse;
  end if;

  select id into v_target_location_id
  from public.locations
  where warehouse_id = v_target_warehouse_id
    and code = trim(p_target_zone)
  limit 1;
  if v_target_location_id is null then
    raise exception 'LOCATION_NOT_FOUND: %', p_target_zone;
  end if;

  insert into public.warehouse_optimizations (
    status, warehouse, source_zones, target_zone, capacity,
    planned_move_count, planned_box_count, operator
  ) values (
    'applying', v_target_warehouse, coalesce(p_source_zones,'[]'::jsonb),
    trim(p_target_zone), v_capacity, jsonb_array_length(p_plan), 0, v_operator
  ) returning id into v_opt_id;

  for v_move in select value from jsonb_array_elements(p_plan) loop
    v_source_warehouse := nullif(trim(v_move->>'source_warehouse'),'');
    v_source_zone := nullif(trim(v_move->>'source_zone'),'');
    v_source_pallet := nullif(trim(v_move->>'source_pallet'),'');
    v_target_warehouse := nullif(trim(v_move->>'target_warehouse'),'');
    v_target_zone := nullif(trim(v_move->>'target_zone'),'');
    v_target_pallet := nullif(trim(v_move->>'target_pallet'),'');
    v_article := nullif(trim(v_move->>'article'),'');

    if jsonb_typeof(v_move->'box_ids') <> 'array' then
      raise exception 'INVALID_BOX_IDS_IN_PLAN';
    end if;

    select array_agg((value)::bigint)
      into v_box_ids
    from jsonb_array_elements_text(v_move->'box_ids') value;

    v_count := coalesce(array_length(v_box_ids,1),0);
    if v_count = 0 then
      raise exception 'EMPTY_BOX_IDS_IN_PLAN';
    end if;

    if v_source_warehouse is null or v_source_zone is null or v_source_pallet is null then
      raise exception 'INVALID_SOURCE_IN_PLAN';
    end if;

    if v_target_warehouse is null or v_target_zone is null or v_target_pallet is null then
      raise exception 'INVALID_TARGET_IN_PLAN';
    end if;

    if v_target_warehouse <> (select warehouse from public.warehouse_optimizations where id=v_opt_id)
       or v_target_zone <> trim(p_target_zone)
       or v_source_warehouse <> (select warehouse from public.warehouse_optimizations where id=v_opt_id) then
      raise exception 'OPTIMIZATION_WAREHOUSE_OR_ZONE_MISMATCH';
    end if;

    -- Every box may occur in the plan only once.
    insert into tmp_skladaplan_opt_boxes(box_id)
    select unnest(v_box_ids)
    on conflict (box_id) do nothing;

    get diagnostics v_actual = row_count;
    if v_actual <> v_count then
      raise exception 'DUPLICATE_BOX_IN_PLAN';
    end if;

    -- Lock all boxes and verify that the plan is still based on current data.
    perform 1 from public.boxes b where b.id = any(v_box_ids) for update;
    select count(*) into v_actual from public.boxes b where b.id = any(v_box_ids);

    if v_actual <> v_count then
      raise exception 'BOX_NOT_FOUND_OR_DELETED';
    end if;

    select count(*) into v_actual
    from public.boxes b
    where b.id = any(v_box_ids)
      and b."Склад" = v_source_warehouse
      and b."Зона/ряд" = v_source_zone
      and b."Поддон" = v_source_pallet
      and b."Статус" = 'На складе'
      and (
        (v_article is null and nullif(trim(coalesce(b."Артикул",'')),'') is null)
        or trim(coalesce(b."Артикул",'')) = coalesce(v_article,'')
      );

    if v_actual <> v_count then
      raise exception 'OPTIMIZATION_CONFLICT: source boxes changed after calculation';
    end if;

    -- Target pallet must belong to the target warehouse/location and be open.
    select p.id, p.warehouse_id, p.location_id, p.pallet_number
      into v_target_pallet_id, v_target_warehouse_id, v_target_location_id, v_target_pallet
    from public.pallets p
    where p.warehouse_id = v_target_warehouse_id
      and p.location_id = v_target_location_id
      and p.pallet_number = v_target_pallet
    for update;

    if v_target_pallet_id is null then
      raise exception 'TARGET_PALLET_NOT_FOUND: %', v_target_pallet;
    end if;

    if exists (select 1 from public.pallets where id=v_target_pallet_id and coalesce(status,'')='Закрыт') then
      raise exception 'TARGET_PALLET_CLOSED: %', v_target_pallet;
    end if;

    select current_count, target_article
      into v_target_count, v_target_article
    from tmp_skladaplan_opt_targets
    where pallet_id = v_target_pallet_id;

    if not found then
      select count(*),
             case when count(distinct nullif(trim(coalesce(b."Артикул",'')),'')) = 0
                  then null
                  when count(distinct nullif(trim(coalesce(b."Артикул",'')),'')) = 1
                  then max(nullif(trim(coalesce(b."Артикул",'')),''))
                  else '__MULTIPLE_ARTICLES__'
             end
        into v_target_count, v_target_article
      from public.boxes b
      where b."Склад" = v_target_warehouse
        and b."Зона/ряд" = v_target_zone
        and b."Поддон" = v_target_pallet
        and b."Статус" = 'На складе';

      if v_target_count >= v_capacity then
        raise exception 'TARGET_PALLET_FULL: %', v_target_pallet;
      end if;

      insert into tmp_skladaplan_opt_targets
        (pallet_id, warehouse_id, location_id, pallet_number, current_count, target_article)
      values
        (v_target_pallet_id, v_target_warehouse_id, v_target_location_id, v_target_pallet,
         v_target_count, v_target_article);
    end if;

    if v_target_article = '__MULTIPLE_ARTICLES__' then
      raise exception 'TARGET_PALLET_HAS_MULTIPLE_ARTICLES: %', v_target_pallet;
    end if;

    if v_target_article is not null and v_article is distinct from v_target_article then
      raise exception 'ARTICLE_MISMATCH_FOR_TARGET_PALLET: %', v_target_pallet;
    end if;

    if v_target_count + v_count > v_capacity then
      raise exception 'TARGET_CAPACITY_EXCEEDED: %', v_target_pallet;
    end if;

    update tmp_skladaplan_opt_targets
    set current_count = current_count + v_count,
        target_article = coalesce(target_article, v_article)
    where pallet_id = v_target_pallet_id;

    insert into public.warehouse_optimization_moves (
      optimization_id, source_warehouse, source_zone, source_pallet,
      target_warehouse, target_zone, target_pallet, article, box_count, box_ids
    ) values (
      v_opt_id, v_source_warehouse, v_source_zone, v_source_pallet,
      v_target_warehouse, v_target_zone, v_target_pallet, v_article, v_count,
      to_jsonb(v_box_ids)
    );

    insert into public.box_movements (
      box_id, barcode, from_warehouse_id, to_warehouse_id,
      from_location_id, to_location_id, from_pallet_id, to_pallet_id,
      from_warehouse_text, to_warehouse_text, from_zone_text, to_zone_text,
      from_pallet_text, to_pallet_text, reason, operator
    )
    select b.id, b."Штрихкод", b.warehouse_id, v_target_warehouse_id,
           b.location_id, v_target_location_id, b.pallet_id, v_target_pallet_id,
           b."Склад", v_target_warehouse, b."Зона/ряд", v_target_zone,
           b."Поддон", v_target_pallet, v_reason, v_operator
    from public.boxes b
    where b.id = any(v_box_ids);

    update public.boxes b
    set "Склад" = v_target_warehouse,
        "Зона/ряд" = v_target_zone,
        "Поддон" = v_target_pallet,
        warehouse_id = v_target_warehouse_id,
        location_id = v_target_location_id,
        pallet_id = v_target_pallet_id,
        "Изменил" = v_operator,
        updated_at = now()
    where b.id = any(v_box_ids);

    get diagnostics v_actual = row_count;
    if v_actual <> v_count then
      raise exception 'OPTIMIZATION_CONFLICT: update count mismatch';
    end if;

    select count(*) into v_existing_source_count
    from public.boxes b
    where b."Склад" = v_source_warehouse
      and b."Зона/ряд" = v_source_zone
      and b."Поддон" = v_source_pallet
      and b."Статус" = 'На складе';

    if v_existing_source_count = 0 then
      v_freed_pallet_count := v_freed_pallet_count + 1;
    end if;

    v_applied_box_count := v_applied_box_count + v_count;
    v_applied_move_count := v_applied_move_count + 1;
  end loop;

  update public.warehouse_optimizations
  set status = 'applied',
      applied_move_count = v_applied_move_count,
      planned_box_count = v_applied_box_count,
      applied_box_count = v_applied_box_count,
      freed_pallet_count = v_freed_pallet_count,
      applied_at = now()
  where id = v_opt_id;

  return jsonb_build_object(
    'optimization_id', v_opt_id,
    'status', 'applied',
    'move_count', v_applied_move_count,
    'box_count', v_applied_box_count,
    'freed_pallet_count', v_freed_pallet_count
  );
exception when others then
  if v_opt_id is not null then
    update public.warehouse_optimizations
    set status='failed', applied_at=now()
    where id=v_opt_id;
  end if;
  raise;
end;
$$;

revoke execute on function public.sp_apply_warehouse_optimization(jsonb,integer,text,text,jsonb) from public;
grant execute on function public.sp_apply_warehouse_optimization(jsonb,integer,text,text,jsonb) to authenticated;

commit;
