-- SKLADAPLAN P0: database safety + RPC contract
-- Run only after backup. This migration is intentionally fail-fast.
-- It does not delete business data.

begin;

-- 1) Reconcile a previously-created legacy movement table.
-- If it contains data, stop rather than silently converting history.
do $$
declare
  bad boolean := false;
  rows_count bigint;
begin
  if to_regclass('public.box_movements') is not null then
    select count(*) into rows_count from public.box_movements;
    select exists (
      select 1
      from information_schema.columns
      where table_schema='public'
        and table_name='box_movements'
        and column_name in ('box_id','from_warehouse_id','to_warehouse_id','from_location_id','to_location_id','from_pallet_id','to_pallet_id')
        and data_type <> 'bigint'
    ) into bad;
    if bad and rows_count > 0 then
      raise exception 'P0 STOP: box_movements contains legacy non-bigint IDs and existing history. Export/reconcile it before migration.';
    elsif bad then
      drop table public.box_movements cascade;
    end if;
  end if;
end $$;

-- 1) Ensure movement table exists with the same bigint FK domain as boxes.
create table if not exists public.box_movements (
  id bigint generated by default as identity primary key,
  box_id bigint references public.boxes(id) on delete set null,
  barcode text,
  from_warehouse_id bigint references public.warehouses(id),
  to_warehouse_id bigint references public.warehouses(id),
  from_location_id bigint references public.locations(id),
  to_location_id bigint references public.locations(id),
  from_pallet_id bigint references public.pallets(id),
  to_pallet_id bigint references public.pallets(id),
  from_warehouse_text text,
  to_warehouse_text text,
  from_zone_text text,
  to_zone_text text,
  from_pallet_text text,
  to_pallet_text text,
  reason text not null default 'move',
  operator text,
  moved_at timestamptz not null default now()
);

alter table public.box_movements enable row level security;

-- 2) Helper: only explicit admin receives write access.
create or replace function public.skladaplan_is_admin()
returns boolean
language sql
stable
security invoker
set search_path = public
as $$
  select coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin';
$$;

revoke all on function public.skladaplan_is_admin() from public;
grant execute on function public.skladaplan_is_admin() to authenticated;

-- 3) Remove legacy anonymous/public write access.
drop policy if exists "Allow public insert boxes" on public.boxes;
drop policy if exists "Allow public update boxes" on public.boxes;
drop policy if exists boxes_insert_authenticated on public.boxes;
drop policy if exists boxes_update_authenticated on public.boxes;
drop policy if exists boxes_delete_authenticated on public.boxes;
drop policy if exists boxes_select_authenticated on public.boxes;

create policy boxes_select_authenticated
  on public.boxes for select to authenticated
  using (true);
create policy boxes_insert_admin
  on public.boxes for insert to authenticated
  with check (public.skladaplan_is_admin());
create policy boxes_update_admin
  on public.boxes for update to authenticated
  using (public.skladaplan_is_admin())
  with check (public.skladaplan_is_admin());
create policy boxes_delete_admin
  on public.boxes for delete to authenticated
  using (public.skladaplan_is_admin());

-- 4) Reference data: authenticated users may read; only admin may write.
drop policy if exists "Allow public read warehouses" on public.warehouses;
create policy warehouses_select_authenticated
  on public.warehouses for select to authenticated using (true);

drop policy if exists "Allow public read locations" on public.locations;
drop policy if exists locations_select_policy on public.locations;
drop policy if exists locations_insert_policy on public.locations;
create policy locations_select_authenticated
  on public.locations for select to authenticated using (true);
create policy locations_insert_admin
  on public.locations for insert to authenticated
  with check (public.skladaplan_is_admin());

 drop policy if exists "Allow public read pallets" on public.pallets;
 drop policy if exists "Allow public insert pallets" on public.pallets;
 drop policy if exists "Allow public update pallets" on public.pallets;
 create policy pallets_select_authenticated
   on public.pallets for select to authenticated using (true);
 create policy pallets_insert_admin
   on public.pallets for insert to authenticated
   with check (public.skladaplan_is_admin());
 create policy pallets_update_admin
   on public.pallets for update to authenticated
   using (public.skladaplan_is_admin())
   with check (public.skladaplan_is_admin());

-- 5) Audit/history: authenticated can read; direct inserts are admin-only.
drop policy if exists inventory_history_insert on public.inventory_history;
drop policy if exists inventory_history_select on public.inventory_history;
create policy inventory_history_select_authenticated
  on public.inventory_history for select to authenticated using (true);
create policy inventory_history_insert_admin
  on public.inventory_history for insert to authenticated
  with check (public.skladaplan_is_admin());

-- 6) Operational tables: viewers read, admins write.
drop policy if exists box_movements_select_authenticated on public.box_movements;
drop policy if exists box_movements_insert_authenticated on public.box_movements;
create policy box_movements_select_authenticated
  on public.box_movements for select to authenticated using (true);
create policy box_movements_insert_admin
  on public.box_movements for insert to authenticated
  with check (public.skladaplan_is_admin());

-- Keep planner/tasks usable as read-only for viewers.
drop policy if exists tasks_all_authenticated on public.tasks;
drop policy if exists planner_tasks_all_authenticated on public.planner_tasks;
drop policy if exists planner_shipments_all_authenticated on public.planner_shipments;
create policy tasks_select_authenticated on public.tasks for select to authenticated using (true);
create policy tasks_admin_write on public.tasks for all to authenticated
  using (public.skladaplan_is_admin()) with check (public.skladaplan_is_admin());
create policy planner_tasks_select_authenticated on public.planner_tasks for select to authenticated using (true);
create policy planner_tasks_admin_write on public.planner_tasks for all to authenticated
  using (public.skladaplan_is_admin()) with check (public.skladaplan_is_admin());
create policy planner_shipments_select_authenticated on public.planner_shipments for select to authenticated using (true);
create policy planner_shipments_admin_write on public.planner_shipments for all to authenticated
  using (public.skladaplan_is_admin()) with check (public.skladaplan_is_admin());

-- 7) Collected verification: viewers read; admins write directly.
alter table public.collected_verification_sessions enable row level security;
alter table public.collected_verification_items enable row level security;
drop policy if exists collected_verification_sessions_all_authenticated on public.collected_verification_sessions;
drop policy if exists collected_verification_items_all_authenticated on public.collected_verification_items;
create policy cv_sessions_select_authenticated on public.collected_verification_sessions for select to authenticated using (true);
create policy cv_sessions_admin_write on public.collected_verification_sessions for all to authenticated
  using (public.skladaplan_is_admin()) with check (public.skladaplan_is_admin());
create policy cv_items_select_authenticated on public.collected_verification_items for select to authenticated using (true);
create policy cv_items_admin_write on public.collected_verification_items for all to authenticated
  using (public.skladaplan_is_admin()) with check (public.skladaplan_is_admin());

-- 8) Notes: viewers read; admins write.
alter table public.pallet_notes enable row level security;
drop policy if exists pallet_notes_all_authenticated on public.pallet_notes;
create policy pallet_notes_select_authenticated on public.pallet_notes for select to authenticated using (true);
create policy pallet_notes_admin_write on public.pallet_notes for all to authenticated
  using (public.skladaplan_is_admin()) with check (public.skladaplan_is_admin());

-- 9) Recreate WMS RPCs with bigint[] IDs and server-side role enforcement.
drop function if exists public.sp_collect_boxes(uuid[], text, text);
drop function if exists public.sp_ship_boxes(uuid[], text);
drop function if exists public.sp_move_boxes(uuid[], text, text, text, text, text);

create or replace function public.sp_collect_boxes(
  p_box_ids bigint[], p_operator text, p_direction text default null
)
returns setof public.boxes
language plpgsql security definer set search_path = public
as $$
begin
  if not public.skladaplan_is_admin() then
    raise exception 'FORBIDDEN: admin role required';
  end if;
  if coalesce(array_length(p_box_ids,1),0) = 0 then
    raise exception 'EMPTY_BOX_LIST';
  end if;
  return query
  update public.boxes
  set "Статус"='Скомплектовано', "Изменил"=p_operator,
      collected_at=now(), collected_by=p_operator,
      "Направление"=coalesce(nullif(p_direction,''),"Направление")
  where id=any(p_box_ids) and "Статус"='КПодбору'
  returning *;
end;
$$;

create or replace function public.sp_ship_boxes(
  p_box_ids bigint[], p_operator text
)
returns setof public.boxes
language plpgsql security definer set search_path = public
as $$
begin
  if not public.skladaplan_is_admin() then
    raise exception 'FORBIDDEN: admin role required';
  end if;
  if coalesce(array_length(p_box_ids,1),0) = 0 then
    raise exception 'EMPTY_BOX_LIST';
  end if;
  return query
  update public.boxes
  set "Статус"='Отгружено', "Изменил"=p_operator,
      shipped_at=now(), shipped_by=p_operator
  where id=any(p_box_ids) and "Статус"='Скомплектовано'
  returning *;
end;
$$;

create or replace function public.sp_move_boxes(
  p_box_ids bigint[], p_target_warehouse text, p_target_zone text,
  p_target_pallet text, p_operator text, p_reason text default 'move'
)
returns setof public.boxes
language plpgsql security definer set search_path = public
as $$
declare
  v_warehouse_id public.warehouses.id%type;
  v_location_id public.locations.id%type;
  v_pallet_id public.pallets.id%type;
  v_count integer;
begin
  if not public.skladaplan_is_admin() then
    raise exception 'FORBIDDEN: admin role required';
  end if;
  if coalesce(array_length(p_box_ids,1),0) = 0 then
    raise exception 'EMPTY_BOX_LIST';
  end if;

  if nullif(trim(p_target_warehouse),'') is not null then
    select id into v_warehouse_id from public.warehouses where name=trim(p_target_warehouse) limit 1;
    if v_warehouse_id is null then raise exception 'WAREHOUSE_NOT_FOUND: %', p_target_warehouse; end if;
  end if;

  if nullif(trim(p_target_zone),'') is not null then
    select id into v_location_id from public.locations
    where code=trim(p_target_zone)
      and (v_warehouse_id is null or warehouse_id=v_warehouse_id) limit 1;
    if v_location_id is null then raise exception 'LOCATION_NOT_FOUND: %', p_target_zone; end if;
  end if;

  if nullif(trim(p_target_pallet),'') is not null then
    select id into v_pallet_id from public.pallets
    where pallet_number=trim(p_target_pallet)
      and (v_warehouse_id is null or warehouse_id=v_warehouse_id) limit 1;
    if v_pallet_id is null then raise exception 'PALLET_NOT_FOUND: %', p_target_pallet; end if;
  end if;

  insert into public.box_movements (
    box_id, barcode, from_warehouse_id, to_warehouse_id,
    from_location_id, to_location_id, from_pallet_id, to_pallet_id,
    from_warehouse_text, to_warehouse_text, from_zone_text, to_zone_text,
    from_pallet_text, to_pallet_text, reason, operator
  )
  select b.id,b."Штрихкод",b.warehouse_id,v_warehouse_id,
         b.location_id,v_location_id,b.pallet_id,v_pallet_id,
         b."Склад",p_target_warehouse,b."Зона/ряд",p_target_zone,
         b."Поддон",p_target_pallet,coalesce(nullif(p_reason,''),'move'),p_operator
  from public.boxes b where b.id=any(p_box_ids);

  update public.boxes
  set "Склад"=coalesce(nullif(trim(p_target_warehouse),''),"Склад"),
      "Зона/ряд"=coalesce(nullif(trim(p_target_zone),''),"Зона/ряд"),
      "Поддон"=coalesce(nullif(trim(p_target_pallet),''),"Поддон"),
      warehouse_id=coalesce(v_warehouse_id,warehouse_id),
      location_id=coalesce(v_location_id,location_id),
      pallet_id=coalesce(v_pallet_id,pallet_id),
      "Изменил"=p_operator
  where id=any(p_box_ids) returning *;
end;
$$;

drop function if exists public.sp_merge_pallets(jsonb, text, text, text, text);
create or replace function public.sp_merge_pallets(
  p_source_pallets jsonb, p_target_warehouse text, p_target_zone text,
  p_target_pallet text, p_operator text
)
returns integer
language plpgsql security definer set search_path = public
as $$
declare
  v_warehouse_id public.warehouses.id%type;
  v_location_id public.locations.id%type;
  v_pallet_id public.pallets.id%type;
  v_moved_count integer;
begin
  if not public.skladaplan_is_admin() then raise exception 'FORBIDDEN: admin role required'; end if;
  if jsonb_typeof(p_source_pallets) <> 'array' or jsonb_array_length(p_source_pallets)=0 then raise exception 'EMPTY_SOURCE_PALLETS'; end if;

  select id into v_warehouse_id from public.warehouses where name=trim(p_target_warehouse) limit 1;
  if v_warehouse_id is null then raise exception 'WAREHOUSE_NOT_FOUND: %', p_target_warehouse; end if;
  select id into v_location_id from public.locations where code=trim(p_target_zone) and warehouse_id=v_warehouse_id limit 1;
  if v_location_id is null then raise exception 'LOCATION_NOT_FOUND: %', p_target_zone; end if;
  select id into v_pallet_id from public.pallets where pallet_number=trim(p_target_pallet) and warehouse_id=v_warehouse_id limit 1;
  if v_pallet_id is null then raise exception 'PALLET_NOT_FOUND: %', p_target_pallet; end if;

  insert into public.box_movements (
    box_id,barcode,from_warehouse_id,to_warehouse_id,from_location_id,to_location_id,
    from_pallet_id,to_pallet_id,from_warehouse_text,to_warehouse_text,from_zone_text,to_zone_text,
    from_pallet_text,to_pallet_text,reason,operator
  )
  select b.id,b."Штрихкод",b.warehouse_id,v_warehouse_id,b.location_id,v_location_id,b.pallet_id,v_pallet_id,
         b."Склад",p_target_warehouse,b."Зона/ряд",p_target_zone,b."Поддон",p_target_pallet,'pallet_merge',p_operator
  from public.boxes b
  where exists (select 1 from jsonb_array_elements(p_source_pallets) s
                where b."Склад"=s->>'warehouse' and b."Зона/ряд"=s->>'zone' and b."Поддон"=s->>'pallet')
    and not (b."Склад"=p_target_warehouse and b."Зона/ряд"=p_target_zone and b."Поддон"=p_target_pallet);

  update public.boxes b
  set "Склад"=p_target_warehouse,"Зона/ряд"=p_target_zone,"Поддон"=p_target_pallet,
      warehouse_id=v_warehouse_id,location_id=v_location_id,pallet_id=v_pallet_id,"Изменил"=p_operator
  where exists (select 1 from jsonb_array_elements(p_source_pallets) s
                where b."Склад"=s->>'warehouse' and b."Зона/ряд"=s->>'zone' and b."Поддон"=s->>'pallet')
    and not (b."Склад"=p_target_warehouse and b."Зона/ряд"=p_target_zone and b."Поддон"=p_target_pallet);
  get diagnostics v_moved_count=row_count;
  return coalesce(v_moved_count,0);
end;
$$;

-- 9) Atomic inventory application. Every UPDATE/INSERT/history row is
-- inside this function's single transaction. Any exception rolls back all changes.
drop function if exists public.sp_apply_inventory(text,text,text,text,timestamptz,text,bigint[],bigint[],text[],bigint,bigint,bigint,integer,integer,jsonb);
create or replace function public.sp_apply_inventory(
  p_warehouse text,
  p_zone text,
  p_pallet text,
  p_started_at timestamptz,
  p_finished_at timestamptz,
  p_operator text,
  p_missing_ids bigint[],
  p_outside_ids bigint[],
  p_unknown_barcodes text[],
  p_target_warehouse_id bigint,
  p_target_location_id bigint,
  p_target_pallet_id bigint,
  p_scanned_count integer,
  p_expected_count integer,
  p_details jsonb
)
returns jsonb
language plpgsql security definer set search_path=public
as $$
declare
  v_operator text := coalesce(auth.jwt()->>'email', p_operator);
  v_removed integer := 0;
  v_moved integer := 0;
  v_created integer := 0;
  v_history_id bigint;
  v_inventory_no bigint;
  v_expected integer := coalesce(p_expected_count,0);
  v_missing integer := coalesce(array_length(p_missing_ids,1),0);
  v_outside integer := coalesce(array_length(p_outside_ids,1),0);
  v_unknown integer := coalesce(array_length(p_unknown_barcodes,1),0);
begin
  if not public.skladaplan_is_admin() then
    raise exception 'FORBIDDEN: admin role required';
  end if;

  if p_target_warehouse_id is null or p_target_location_id is null or p_target_pallet_id is null then
    raise exception 'INVALID_INVENTORY_TARGET';
  end if;

  update public.boxes
  set "Поддон"=null, pallet_id=null, "Изменил"=v_operator
  where id=any(coalesce(p_missing_ids,'{}'::bigint[]))
    and "Склад"=p_warehouse
    and "Зона/ряд"=p_zone
    and ("Поддон"=p_pallet or pallet_id=p_target_pallet_id);
  get diagnostics v_removed=row_count;
  if v_removed <> v_missing then
    raise exception 'INVENTORY_CONFLICT: expected % missing updates, changed %', v_missing, v_removed;
  end if;

  update public.boxes
  set "Склад"=p_warehouse, "Зона/ряд"=p_zone, "Поддон"=p_pallet,
      warehouse_id=p_target_warehouse_id, location_id=p_target_location_id,
      pallet_id=p_target_pallet_id, "Изменил"=v_operator
  where id=any(coalesce(p_outside_ids,'{}'::bigint[]));
  get diagnostics v_moved=row_count;
  if v_moved <> v_outside then
    raise exception 'INVENTORY_CONFLICT: expected % outside updates, changed %', v_outside, v_moved;
  end if;

  if v_unknown > 0 then
    insert into public.boxes (
      "Штрихкод","Артикул","Кол-во в коробке","Зона/ряд","Поддон","Статус",
      "ДатаРазмещения","Склад","Изменил",warehouse_id,location_id,pallet_id
    )
    select b,null,null,p_zone,p_pallet,'На складе',current_date,p_warehouse,v_operator,
           p_target_warehouse_id,p_target_location_id,p_target_pallet_id
    from unnest(p_unknown_barcodes) as u(b);
    get diagnostics v_created=row_count;
  end if;

  insert into public.inventory_history (
    warehouse,zone,pallet,started_at,finished_at,applied_at,user_email,
    expected_count,scanned_count,missing_count,outside_count,unknown_count,
    actual_count,moved_count,removed_count,created_count,details
  ) values (
    p_warehouse,p_zone,p_pallet,p_started_at,p_finished_at,now(),v_operator,
    v_expected,coalesce(p_scanned_count,0),v_missing,v_outside,v_unknown,
    coalesce(p_scanned_count,0)+v_outside+v_unknown,v_moved,v_removed,v_created,
    coalesce(p_details,'{}'::jsonb)
  )
  returning id,inventory_no into v_history_id,v_inventory_no;

  return jsonb_build_object(
    'history_id',v_history_id,
    'inventory_no',v_inventory_no,
    'moved_count',v_moved,
    'removed_count',v_removed,
    'created_count',v_created
  );
end;
$$;

revoke execute on function public.sp_collect_boxes(bigint[],text,text) from public;
revoke execute on function public.sp_ship_boxes(bigint[],text) from public;
revoke execute on function public.sp_move_boxes(bigint[],text,text,text,text,text) from public;
revoke execute on function public.sp_merge_pallets(jsonb,text,text,text,text) from public;
grant execute on function public.sp_collect_boxes(bigint[],text,text) to authenticated;
grant execute on function public.sp_ship_boxes(bigint[],text) to authenticated;
grant execute on function public.sp_move_boxes(bigint[],text,text,text,text,text) to authenticated;
grant execute on function public.sp_merge_pallets(jsonb,text,text,text) to authenticated;

commit;
